os: osx
language: swift
osx_image: xcode11.1
script: xcodebuild clean build test -workspace App/Nearby.xcworkspace -scheme "Nearby" -sdk iphonesimulator -destination "platform=iOS Simulator,OS=11.4,name=iPhone 8" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO