# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Nearby' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Nearby
  pod 'FoursquareAPIClient'
  pod 'Nuke'
  pod 'Unrealm'
  pod 'SwiftLint'

  target 'NearbyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NearbyUITests' do
    # Pods for testing
  end

end
